version: '3'

services:
  go:
    build: ./go
    ports:
      - "8080:8080"
  nextjs:
    build: ./nextjs
    ports:
      - "3000:3000"
  wordpress:
    build: ./wordpress
    ports:
      - "80:80"
